### ISSUE TITLE
Do not display type if underlying state is error

### ISSUE THREAD

**Issue by loxs** [Khady/merlin-eldoc#17]
Hi, I have been using the package with Spacemacs and while I am delighted with how useful it is, it conflicts with the functionality which is on by default in spacemacs, which is to display errors on hover.

I am not at all familiar with emacs scripting, so hopefully this is not a very stupid suggestion, but is it possible to not display the type if the state under cursor is an error, but instead let spacemacs display the error message?

Or perhaps it's reasonable to display error at cursor in merlin-eldoc itself?

**Comment by Khady** [comment]
This is actually not specific to spacemacs. merlin automatically calls `merlin-show-error-on-current-line` after an idle of 0.5s. I don't think the error should be displayed by merlin-eldoc.

Do you know if spacemacs is relying on merlin-show-error-on-current-line or something else?

**Comment by Khady** [comment]
@loxs please let me know if 1b1c756 fixes the problem in spacemacs.

**Comment by loxs** [comment]
I don't know what it calls, but your latest version now works perfectly for me. Thanks!

**Comment by Khady** [comment]
Thanks for the report.
