### ISSUE TITLE
Infix operators documentation

### ISSUE THREAD

**Issue by Fourchaux** [Khady/merlin-eldoc#19]
First of all, thanks for this useful package. :+1: 

Currently, it seems that no doc is available for the infix operators.
For example, with your example 5, no doc is displayed if the cursor is at '**@@**'.

However, using e.g.,  ```M-x merlin-document``` at the same location shows the full documentation.
Is it possible to have this behavior?

**Comment by Khady** [comment]
Yes it is possible. I need to fix the code detecting the valid positions where eldoc can be triggered. Will try to do this soon.

**Comment by Khady** [comment]
@Fourchaux this is fixed in master. Please let me know if there is a problem.

**Comment by Fourchaux** [comment]
Okey! 
Everything is working.

Thank you.
