### ISSUE TITLE
Display type structure instead of only type name

### ISSUE THREAD

**Issue by loxs** [Khady/merlin-eldoc#20]
When you hover over a record variable, it shows something like:
```ocaml
Module.record_name
```

Instead, it would be better if we get something like
```ocaml
type record_name = {
    ModuleName.record_field; 
    ...
}
```

Sometimes I actually do get this (what I request), but only in some contexts like in function heads, which IMO is not enough. I am forced to "go to definition" too often

It happens with other types as well, but it's most annoying with records so far.

**Comment by Khady** [comment]
This is a deliberate behavior. I was considering that if one wants to see more details about the type, one would call merlin by hand. But it could be adjusted.

When the type of a value is requested using `merlin-type-enclosing`, It shows the most abstract version of the type. This is what is done by merlin-eldoc.

Merlin offers a mechanism to see a non abstract version of the type. By calling `merlin-type-enclosing` multiple times in a row on the same value, it goes down in the abstraction level and shows more information.

It is possible to have something in merlin-eldoc which would show non abstract types. The question is how to control it.

- Always go to the deepest level available?
- Provide a configuration setting with:
  - go as deep as possible
  - go to level X
  In this case what should be the default?
- Use a behavior like merlin. If merlin-eldoc is activated multiple times in a row at the same point, go to the next level.

**Comment by loxs** [comment]
Hm, I didn't know about the multiple invocations of Merlin. This certainly will make my life easier a lot. 

I don't know about the implications of "always go to the deepest level". To my newbie self, this sounds quite nice, as I still don't have lots of experience and I haven't encountered a place where I wouldn't want that.

Now, if there is some way to do your last suggestion, that would be perfect, but I'm not sure how would it work. How would you activate merlin-eldoc multiple times? Move one character within the same value and wait some more? That would be nicer than pressing the combination for `merlin-type-enclosing` one more time for sure... though I don't know about values which are only one char.
