### ISSUE TITLE
Support navigating between occurrences

### ISSUE THREAD

**Issue by Wilfred** [Khady/merlin-eldoc#25]
It would be wonderful to have a command that allowed moving point between the different occurrences of a symbol.

**Comment by Khady** [comment]
I think this is more related to merlin than merlin-eldoc. M-x merlin-occurrences opens a buffer with all the other occurrences and a way to jump to any of them. It seems to be a pretty standard behavior. I don't know if it is possible to build keybindings on top of that. Or if it would be better to have such a keybinding in merlin-eldoc.

**Comment by Khady** [comment]
@wilfred I'm willing to add this feature. Not sure of how to do this properly. And you seem to be experienced with emacs development. So it would be wonderful if you could guide me a little.

Do you think I should just create a function and let users bind it? Or it would be better to create a map? Or extend the one provided by merlin?

The last option is probably not very nice as in theory it is possible to use merlin-eldoc without merlin-mode.

If I have an option to loop once the end of the list is reached, should it display a message saying "end of file reached, searching from top" or something similar?

**Comment by Khady** [comment]
@Wilfred I added to functions to jump between occurrences. Please let me know if it works for you.

**Comment by Wilfred** [comment]
@Khady that works wonderfully! Thank you :)
